---
# Przykładowy playbook zbierający informacje o partycji IBM i

- hosts: asy    
  remote_user: ansible
  gather_facts: False

  tasks:
    - name: Zbieranie profilu użytkownika
      ibm.power_ibmi.ibmi_user_and_group:
        operation: 'create'
        user: '{{ as_user }}'  
        password: '{{ as_pass }}' 
        user_class: "*USER"
      register: prof

    - name: Wyświetlanie profilu użytkownika
      debug:
        var: prof
